-- begin CEUW_ADDRESS
alter table CEUW_ADDRESS add constraint FK_CEUW_ADDRESS_ON_CUSTOMER foreign key (CUSTOMER_ID) references CEUW_CUSTOMER(ID)^
create index IDX_CEUW_ADDRESS_ON_CUSTOMER on CEUW_ADDRESS (CUSTOMER_ID)^
-- end CEUW_ADDRESS
-- begin CEUW_ORDER
alter table CEUW_ORDER add constraint FK_CEUW_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CEUW_CUSTOMER(ID)^
alter table CEUW_ORDER add constraint FK_CEUW_ORDER_ON_DELIVERY_ADDRESS foreign key (DELIVERY_ADDRESS_ID) references CEUW_ADDRESS(ID)^
alter table CEUW_ORDER add constraint FK_CEUW_ORDER_ON_INVOICE_ADDRESS foreign key (INVOICE_ADDRESS_ID) references CEUW_ADDRESS(ID)^
create index IDX_CEUW_ORDER_ON_CUSTOMER on CEUW_ORDER (CUSTOMER_ID)^
create index IDX_CEUW_ORDER_ON_DELIVERY_ADDRESS on CEUW_ORDER (DELIVERY_ADDRESS_ID)^
create index IDX_CEUW_ORDER_ON_INVOICE_ADDRESS on CEUW_ORDER (INVOICE_ADDRESS_ID)^
-- end CEUW_ORDER
-- begin CEUW_ORDER_LINE
alter table CEUW_ORDER_LINE add constraint FK_CEUW_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references CEUW_PRODUCT(ID)^
alter table CEUW_ORDER_LINE add constraint FK_CEUW_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references CEUW_ORDER(ID)^
create index IDX_CEUW_ORDER_LINE_ON_PRODUCT on CEUW_ORDER_LINE (PRODUCT_ID)^
create index IDX_CEUW_ORDER_LINE_ON_ORDER on CEUW_ORDER_LINE (ORDER_ID)^
-- end CEUW_ORDER_LINE
-- begin CEUW_PRODUCT_PRICE
alter table CEUW_PRODUCT_PRICE add constraint FK_CEUW_PRODUCT_PRICE_ON_PRODUCT foreign key (PRODUCT_ID) references CEUW_PRODUCT(ID)^
create index IDX_CEUW_PRODUCT_PRICE_ON_PRODUCT on CEUW_PRODUCT_PRICE (PRODUCT_ID)^
-- end CEUW_PRODUCT_PRICE
